# 50日間コミットしないと403エラーが発生するため、空コミットを自動で行う
name: Prevent 403 Error by Regular Commit

on:
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜日の午前0時に実行
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create an empty commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit --allow-empty -m "Keep GitHub Actions alive"

      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/Akihide-Tsue/auto_mf_actions
          git push origin main
        env:
          PAT: ${{ secrets.PAT }}
