name: Auto record

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "40 0 * * *" # 日本時間9:40に実行
    - cron: "20 10 * * *" # 日本時間19:20に実行

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # キャッシュ
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      # インストール
      - name: npm install command
        run: npm install

      # 実際のコマンド
      - name: main action...
        run: >
          node main.js
